export const iqDuelQuestions = [
  {
    game_slug: 'iq-duel',
    question_text: 'Which country has the most natural lakes in the world?',
    answer_type: 'multiple_choice',
    options: ['United States', 'Canada', 'Russia', 'Finland'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If 5 cats can catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?',
    answer_type: 'multiple_choice',
    options: ['100 cats', '5 cats', '20 cats', '1 cat'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which chemical element has the symbol "Au"?',
    answer_type: 'multiple_choice',
    options: ['Silver', 'Copper', 'Gold', 'Aluminum'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Complete the pattern: 2, 6, 12, 20, 30, __?',
    answer_type: 'multiple_choice',
    options: ['38', '40', '42', '44'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the speed of light in vacuum (approximate)?',
    answer_type: 'multiple_choice',
    options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'],
    correct_index: 0,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'A bat and a ball together cost $1.10. The bat costs $1.00 more than the ball. How much does the ball cost?',
    answer_type: 'multiple_choice',
    options: ['$0.10', '$0.05', '$0.15', '$0.01'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which planet in our solar system has the shortest day (fastest rotation)?',
    answer_type: 'multiple_choice',
    options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If yesterday was Tuesday, what day will it be 3 days after tomorrow?',
    answer_type: 'multiple_choice',
    options: ['Saturday', 'Sunday', 'Monday', 'Friday'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the only organ in the human body capable of regenerating itself?',
    answer_type: 'multiple_choice',
    options: ['Heart', 'Liver', 'Kidney', 'Lungs'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which number is missing in the sequence: 1, 1, 2, 3, 5, 8, 13, __?',
    answer_type: 'multiple_choice',
    options: ['18', '20', '21', '25'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What gas makes up approximately 78% of Earth’s atmosphere?',
    answer_type: 'multiple_choice',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: '👑 FINAL DOUBLE-POINT QUESTION: If a doctor gives you 3 pills and tells you to take one every 30 minutes, how long will they last?',
    answer_type: 'multiple_choice',
    options: ['90 minutes', '60 minutes', '30 minutes', '120 minutes'],
    correct_index: 1,
    weight: 2,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which ocean is the deepest in the world?',
    answer_type: 'multiple_choice',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'How many sides does a nonagon have?',
    answer_type: 'multiple_choice',
    options: ['7', '8', '9', '10'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If you rearrange the letters "CINEMA", you get which word related to reading?',
    answer_type: 'multiple_choice',
    options: ['ICEMAN', 'ANIME', 'ICEMEN', 'ICEMAN'],
    correct_index: 0,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the capital city of Australia?',
    answer_type: 'multiple_choice',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which organ produces insulin in the human body?',
    answer_type: 'multiple_choice',
    options: ['Liver', 'Pancreas', 'Gallbladder', 'Spleen'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If an electric train is traveling south at 60 mph and the wind is blowing north at 20 mph, which way does the smoke blow?',
    answer_type: 'multiple_choice',
    options: ['North', 'South', 'East', 'Electric trains do not emit smoke!'],
    correct_index: 3,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the sum of angles inside a hexagon?',
    answer_type: 'multiple_choice',
    options: ['360 degrees', '540 degrees', '720 degrees', '900 degrees'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: '👑 MARATHON GRAND FINAL QUESTION: Some months have 31 days, some have 30 days. How many months have 28 days?',
    answer_type: 'multiple_choice',
    options: ['1 month (February)', '6 months', '12 months', '2 months'],
    correct_index: 2,
    weight: 2,
  },
  { game_slug: 'iq-duel', question_text: 'What is the powerhouse of the cell?', answer_type: 'multiple_choice', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic Reticulum'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Who wrote the play "Romeo and Juliet"?', answer_type: 'multiple_choice', options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the largest mammal on Earth?', answer_type: 'multiple_choice', options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the chemical symbol for Silver?', answer_type: 'multiple_choice', options: ['Ag', 'Au', 'Si', 'Sr'], correct_index: 0, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Which planet is known as the Red Planet?', answer_type: 'multiple_choice', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'In what year did the Titanic sink?', answer_type: 'multiple_choice', options: ['1910', '1912', '1914', '1916'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the hardest natural substance on Earth?', answer_type: 'multiple_choice', options: ['Gold', 'Iron', 'Diamond', 'Platinum'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'How many continents are there?', answer_type: 'multiple_choice', options: ['5', '6', '7', '8'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Who painted the Mona Lisa?', answer_type: 'multiple_choice', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the square root of 144?', answer_type: 'multiple_choice', options: ['10', '11', '12', '14'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Which animal is known as the King of the Jungle?', answer_type: 'multiple_choice', options: ['Tiger', 'Lion', 'Elephant', 'Gorilla'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the longest river in the world?', answer_type: 'multiple_choice', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'How many bones are in the adult human body?', answer_type: 'multiple_choice', options: ['206', '208', '210', '212'], correct_index: 0, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the capital of Japan?', answer_type: 'multiple_choice', options: ['Beijing', 'Seoul', 'Tokyo', 'Bangkok'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Which gas do plants absorb from the atmosphere?', answer_type: 'multiple_choice', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'Who was the first man to walk on the moon?', answer_type: 'multiple_choice', options: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Michael Collins'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the smallest prime number?', answer_type: 'multiple_choice', options: ['0', '1', '2', '3'], correct_index: 2, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'In which city is the Eiffel Tower located?', answer_type: 'multiple_choice', options: ['London', 'Berlin', 'Rome', 'Paris'], correct_index: 3, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'What is the primary ingredient in hummus?', answer_type: 'multiple_choice', options: ['Lentils', 'Chickpeas', 'Black beans', 'Pinto beans'], correct_index: 1, weight: 1 },
  { game_slug: 'iq-duel', question_text: 'How many days are in a leap year?', answer_type: 'multiple_choice', options: ['364', '365', '366', '367'], correct_index: 2, weight: 1 }

];
