export const iqDuelQuestions = [
  {
    game_slug: 'iq-duel',
    question_text: 'Which country has the most natural lakes in the world?',
    answer_type: 'multiple_choice',
    options: ['United States', 'Canada', 'Russia', 'Finland'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If 5 cats can catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?',
    answer_type: 'multiple_choice',
    options: ['100 cats', '5 cats', '20 cats', '1 cat'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which chemical element has the symbol "Au"?',
    answer_type: 'multiple_choice',
    options: ['Silver', 'Copper', 'Gold', 'Aluminum'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Complete the pattern: 2, 6, 12, 20, 30, __?',
    answer_type: 'multiple_choice',
    options: ['38', '40', '42', '44'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the speed of light in vacuum (approximate)?',
    answer_type: 'multiple_choice',
    options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'],
    correct_index: 0,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'A bat and a ball together cost $1.10. The bat costs $1.00 more than the ball. How much does the ball cost?',
    answer_type: 'multiple_choice',
    options: ['$0.10', '$0.05', '$0.15', '$0.01'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which planet in our solar system has the shortest day (fastest rotation)?',
    answer_type: 'multiple_choice',
    options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If yesterday was Tuesday, what day will it be 3 days after tomorrow?',
    answer_type: 'multiple_choice',
    options: ['Saturday', 'Sunday', 'Monday', 'Friday'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the only organ in the human body capable of regenerating itself?',
    answer_type: 'multiple_choice',
    options: ['Heart', 'Liver', 'Kidney', 'Lungs'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which number is missing in the sequence: 1, 1, 2, 3, 5, 8, 13, __?',
    answer_type: 'multiple_choice',
    options: ['18', '20', '21', '25'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What gas makes up approximately 78% of Earth’s atmosphere?',
    answer_type: 'multiple_choice',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: '👑 FINAL DOUBLE-POINT QUESTION: If a doctor gives you 3 pills and tells you to take one every 30 minutes, how long will they last?',
    answer_type: 'multiple_choice',
    options: ['90 minutes', '60 minutes', '30 minutes', '120 minutes'],
    correct_index: 1,
    weight: 2,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which ocean is the deepest in the world?',
    answer_type: 'multiple_choice',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'How many sides does a nonagon have?',
    answer_type: 'multiple_choice',
    options: ['7', '8', '9', '10'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If you rearrange the letters "CINEMA", you get which word related to reading?',
    answer_type: 'multiple_choice',
    options: ['ICEMAN', 'ANIME', 'ICEMEN', 'ICEMAN'],
    correct_index: 0,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the capital city of Australia?',
    answer_type: 'multiple_choice',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'Which organ produces insulin in the human body?',
    answer_type: 'multiple_choice',
    options: ['Liver', 'Pancreas', 'Gallbladder', 'Spleen'],
    correct_index: 1,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'If an electric train is traveling south at 60 mph and the wind is blowing north at 20 mph, which way does the smoke blow?',
    answer_type: 'multiple_choice',
    options: ['North', 'South', 'East', 'Electric trains do not emit smoke!'],
    correct_index: 3,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: 'What is the sum of angles inside a hexagon?',
    answer_type: 'multiple_choice',
    options: ['360 degrees', '540 degrees', '720 degrees', '900 degrees'],
    correct_index: 2,
    weight: 1,
  },
  {
    game_slug: 'iq-duel',
    question_text: '👑 MARATHON GRAND FINAL QUESTION: Some months have 31 days, some have 30 days. How many months have 28 days?',
    answer_type: 'multiple_choice',
    options: ['1 month (February)', '6 months', '12 months', '2 months'],
    correct_index: 2,
    weight: 2,
  },
];
