export const knowMeCategories = [
  {
    id: 'e033322a-b726-4792-a459-88300e7f41db',
    game_slug: 'know-me',
    name: 'Long Distance',
    emoji: '✈️',
    description: 'Airport reunions, time zones, screen dates & late night calls',
    color: 'text-sky-400',
    badge_bg: 'bg-sky-500/10 border-sky-500/30',
    display_order: 10,
  },
  {
    id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    game_slug: 'know-me',
    name: 'Pop Culture',
    emoji: '🎬',
    description: 'Movies, music taste, viral trends & celebrity crushes',
    color: 'text-purple-400',
    badge_bg: 'bg-purple-500/10 border-border',
    display_order: 20,
  },
  {
    id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    game_slug: 'know-me',
    name: 'Most Likely To',
    emoji: '👉',
    description: 'Who is most likely to do what? Cast your votes!',
    color: 'text-amber-400',
    badge_bg: 'bg-amber-500/10 border-amber-500/30',
    display_order: 30,
  },
  {
    id: 'c9df3175-9510-4746-9f10-2a84b9c88e40',
    game_slug: 'know-me',
    name: 'Cute & Wholesome',
    emoji: '🥰',
    description: 'Sweet moments, cuddle styles & romantic gestures',
    color: 'text-rose-400',
    badge_bg: 'bg-rose-500/10 border-border',
    display_order: 40,
  },
  {
    id: '2cf0cdaf-68e4-4a23-aead-2b7d2f35bae4',
    game_slug: 'know-me',
    name: 'After Dark',
    emoji: '🌙',
    description: 'Intimate desires, night vibes & pillow talk confessions',
    color: 'text-indigo-400',
    badge_bg: 'bg-indigo-500/10 border-indigo-500/30',
    display_order: 50,
  },
  {
    id: '1f942da4-6241-47b9-8097-e63c9d473f7a',
    game_slug: 'know-me',
    name: 'Spicy',
    emoji: '🔥',
    description: 'Wild questions, secret turn-ons & bold fantasies',
    color: 'text-red-400',
    badge_bg: 'bg-red-500/10 border-red-500/30',
    display_order: 60,
  },
  {
    id: '633ebce0-183b-4fbe-a9da-dafb36fe6a17',
    game_slug: 'know-me',
    name: 'Deep Questions',
    emoji: '🌊',
    description: 'Core values, life philosophies & vulnerabilities',
    color: 'text-blue-400',
    badge_bg: 'bg-blue-500/10 border-blue-500/30',
    display_order: 70,
  },
  {
    id: '7352a310-464a-49ce-b491-6d1196c7bdee',
    game_slug: 'know-me',
    name: 'Foodies',
    emoji: '🍔',
    description: 'Midnight snacks, dream dinner dates & food habits',
    color: 'text-orange-400',
    badge_bg: 'bg-orange-500/10 border-orange-500/30',
    display_order: 80,
  },
  {
    id: 'c02895de-079d-4300-baf9-727a19e58e66',
    game_slug: 'know-me',
    name: 'Firsts & Memories',
    emoji: '📸',
    description: 'First impressions, early texts & unforgettable moments',
    color: 'text-pink-400',
    badge_bg: 'bg-pink-500/10 border-border',
    display_order: 90,
  },
  {
    id: 'd0a9567e-f400-414f-82a9-24f562d15067',
    game_slug: 'know-me',
    name: 'Silly & Random',
    emoji: '🤪',
    description: 'Weird habits, alien theories & hilarious hypotheticals',
    color: 'text-yellow-400',
    badge_bg: 'bg-yellow-500/10 border-yellow-500/30',
    display_order: 100,
  },
  {
    id: '342055b5-acbc-48d0-9347-0a09ec4217cc',
    game_slug: 'know-me',
    name: 'Adventure & Travel',
    emoji: '🌍',
    description: 'Bucket list trips, thrill seeking & dream destinations',
    color: 'text-emerald-400',
    badge_bg: 'bg-emerald-500/10 border-border',
    display_order: 110,
  },
  {
    id: '6006c2f7-c451-427a-952b-485019438ca0',
    game_slug: 'know-me',
    name: 'Red Flags & Icks',
    emoji: '🚩',
    description: 'Dealbreakers, pet peeves & funny relationship icks',
    color: 'text-rose-600',
    badge_bg: 'bg-rose-900/20 border-rose-600/30',
    display_order: 120,
  },
  {
    id: 'abf5d323-6501-4d27-ac32-b2441c85c940',
    game_slug: 'know-me',
    name: 'Throwback Nostalgia',
    emoji: '📼',
    description: 'Childhood memories, old school music & growing up',
    color: 'text-teal-400',
    badge_bg: 'bg-teal-500/10 border-teal-500/30',
    display_order: 130,
  },
  {
    id: 'eaf58a21-7ade-4b03-9c21-d4ade4f75032',
    game_slug: 'know-me',
    name: 'Our Future',
    emoji: '✨',
    description: 'Closing the distance, dream home & long term plans',
    color: 'text-violet-400',
    badge_bg: 'bg-violet-500/10 border-violet-500/30',
    display_order: 140,
  },
  {
    id: '62df1e57-3984-474d-a891-e2794be9d6fd',
    game_slug: 'know-me',
    name: 'Secrets & Confessions',
    emoji: '🤫',
    description: 'Little secrets, funny truths & unspoken thoughts',
    color: 'text-cyan-400',
    badge_bg: 'bg-cyan-500/10 border-cyan-500/30',
    display_order: 150,
  },
  {
    id: '987b773f-494f-484a-a100-1c127dfc8eeb',
    game_slug: 'know-me',
    name: 'Hot Takes',
    emoji: '🌶️',
    description: 'Controversial opinions on food, romance & life',
    color: 'text-orange-500',
    badge_bg: 'bg-orange-500/20 border-orange-500/40',
    display_order: 160,
  },
  {
    id: '4427023a-f221-464c-b00b-70c383977f07',
    game_slug: 'know-me',
    name: 'What If...?',
    emoji: '🔮',
    description: 'Wild scenarios, apocalypse partners & time travel',
    color: 'text-fuchsia-400',
    badge_bg: 'bg-fuchsia-500/10 border-fuchsia-500/30',
    display_order: 170,
  },
];

export const knowMeQuestions = [
  {
    category_id: 'e033322a-b726-4792-a459-88300e7f41db',
    question_text: 'What is my favorite thing to do during our long distance video calls?',
    answer_type: 'multiple_choice',
    options: ['Falling asleep together', 'Watching movies/shows together', 'Just talking about our day', 'Eating meals together on camera'],
  },
  {
    category_id: 'e033322a-b726-4792-a459-88300e7f41db',
    question_text: 'How do I handle missing you the most?',
    answer_type: 'multiple_choice',
    options: ['Listen to our playlist', 'Reread old messages & letters', 'Look at our photos', 'Text you right away'],
  },
  {
    category_id: 'e033322a-b726-4792-a459-88300e7f41db',
    question_text: 'What is my biggest long-distance pet peeve?',
    answer_type: 'multiple_choice',
    options: ['Bad Wi-Fi connection during a deep call', 'Time zone math confusion', 'Not being able to give you a real hug', 'Flight delays & airport waits'],
  },
  {
    category_id: 'e033322a-b726-4792-a459-88300e7f41db',
    question_text: 'Which virtual date idea is my absolute favorite?',
    answer_type: 'multiple_choice',
    options: ['Virtual museum / Google Earth tour', 'Online multiplayer gaming session', 'Ordering food to each other\'s doorstep', 'Simultaneous movie watch-party'],
  },
  {
    category_id: 'e033322a-b726-4792-a459-88300e7f41db',
    question_text: 'What is the first thing I want to do the exact moment we meet at the airport?',
    answer_type: 'multiple_choice',
    options: ['Give you the longest tightest hug', 'Kiss you like in a movie', 'Look in your eyes and laugh with joy', 'Grab your hand and head to get food'],
  },
  {
    category_id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    question_text: 'If we were stuck in a movie universe, which one would I pick?',
    answer_type: 'multiple_choice',
    options: ['Marvel Cinematic Universe', 'Harry Potter Wizarding World', 'Studio Ghibli / Anime', 'Classic Romantic Comedy'],
  },
  {
    category_id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    question_text: 'What is my ultimate go-to music genre when I am happy?',
    answer_type: 'multiple_choice',
    options: ['R&B / Soul', 'Pop / Upbeat', 'Indie / Acoustic', 'Afrobeats / Dancehall'],
  },
  {
    category_id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    question_text: 'Who is my secret celebrity crush that I would never stop talking about?',
    answer_type: 'multiple_choice',
    options: ['Zendaya / Timothée Chalamet', 'Michael B. Jordan / Rihanna', 'Ryan Gosling / Margot Robbie', 'Pedro Pascal / Ana de Armas'],
  },
  {
    category_id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    question_text: 'How do I behave when watching a suspenseful horror or thriller movie?',
    answer_type: 'multiple_choice',
    options: ['Hide under the blanket & peek', 'Predict every plot twist out loud', 'Super calm & unaffected', 'Scream at jump scares'],
  },
  {
    category_id: '18ca123a-ba5e-48f3-956a-722ec5313f4c',
    question_text: 'If we made a joint couple TikTok or Reel, what type would it be?',
    answer_type: 'multiple_choice',
    options: ['A cute LDR reunion video', 'A funny trending audio joke', 'A travel vlog / aesthetic edit', 'A cooking / food tasting review'],
  },
  {
    category_id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    question_text: 'Who is most likely to cry during an emotional movie scene?',
    answer_type: 'multiple_choice',
    options: ['Alex', 'Taylor', 'Both of us equally', 'Neither of us'],
  },
  {
    category_id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    question_text: 'Who is most likely to splurge on something unneeded but cute?',
    answer_type: 'multiple_choice',
    options: ['Alex', 'Taylor', 'Definitely both', 'Neither'],
  },
  {
    category_id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    question_text: 'Who is most likely to fall asleep first during a movie night?',
    answer_type: 'multiple_choice',
    options: ['Alex', 'Taylor', 'Whoever had a longer day', 'We both stay awake all night'],
  },
  {
    category_id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    question_text: 'Who is most likely to get lost when navigating in a new city?',
    answer_type: 'multiple_choice',
    options: ['Alex', 'Taylor', 'Google Maps glitches on both', 'Neither, we are human GPS'],
  },
  {
    category_id: '2563b0ea-ac2e-4957-ba47-d42836ce479f',
    question_text: 'Who is most likely to start a playful food fight in the kitchen?',
    answer_type: 'multiple_choice',
    options: ['Alex', 'Taylor', 'Both at the same time', 'We respect food too much'],
  },
  {
    category_id: 'c9df3175-9510-4746-9f10-2a84b9c88e40',
    question_text: 'What is my absolute favorite physical affection when we are together?',
    answer_type: 'multiple_choice',
    options: ['Forehead kisses', 'Holding hands tight', 'Long warm hugs', 'Cuddling under blankets'],
  },
  {
    category_id: 'c9df3175-9510-4746-9f10-2a84b9c88e40',
    question_text: 'What sweet gesture from you makes my heart melt instantly?',
    answer_type: 'multiple_choice',
    options: ['Unexpected good morning texts', 'Remembering a tiny detail I mentioned weeks ago', 'Sending cute photos/selfies randomly', 'Calling me sweet nicknames'],
  },
  {
    category_id: 'c9df3175-9510-4746-9f10-2a84b9c88e40',
    question_text: 'If I were a cute animal emoji, which one represents me best?',
    answer_type: 'multiple_choice',
    options: ['🧸 Teddy bear', '🐱 Cozy kitten', '🐶 Playful puppy', '🐰 Bunny'],
  },
  {
    category_id: 'c9df3175-9510-4746-9f10-2a84b9c88e40',
    question_text: 'What is my favorite nickname you call me?',
    answer_type: 'multiple_choice',
    options: ['Babe / Baby', 'My love', 'Honey / Sweetheart', 'A unique private nickname'],
  },
  {
    category_id: '2cf0cdaf-68e4-4a23-aead-2b7d2f35bae4',
    question_text: 'What late night mood fits me best when we are together in person?',
    answer_type: 'multiple_choice',
    options: ['Sweet & slow romance', 'Playful & teasing', 'Passionate & intense', 'Deep pillow talk till morning'],
  },
  {
    category_id: '2cf0cdaf-68e4-4a23-aead-2b7d2f35bae4',
    question_text: 'What is my favorite time of night for intimate conversations?',
    answer_type: 'multiple_choice',
    options: ['Right before falling asleep', '1 AM midnight vibe', '3 AM deep hours', 'Early morning right after waking up'],
  },
  {
    category_id: '2cf0cdaf-68e4-4a23-aead-2b7d2f35bae4',
    question_text: 'When we are physically together, what setting is most romantic to me?',
    answer_type: 'multiple_choice',
    options: ['Dim candlelight with soft music', 'Rainy night with cozy blankets', 'Moonlight view by the window', 'Warm bubble bath together'],
  },
  {
    category_id: '1f942da4-6241-47b9-8097-e63c9d473f7a',
    question_text: 'What turns me on the quickest?',
    answer_type: 'multiple_choice',
    options: ['A deep sultry voice over the phone', 'Unexpected romantic touch', 'Flirty tease texts during the day', 'Getting dressed up elegant'],
  },
  {
    category_id: '1f942da4-6241-47b9-8097-e63c9d473f7a',
    question_text: 'What is my favorite type of spicy text from you?',
    answer_type: 'multiple_choice',
    options: ['Teasing photos / outfit peeks', 'Bold confessions of what you want to do', 'Audio voice notes', 'Flirty countdown reminders'],
  },
  {
    category_id: '1f942da4-6241-47b9-8097-e63c9d473f7a',
    question_text: 'What is a spicy fantasy location we should try when we meet?',
    answer_type: 'multiple_choice',
    options: ['Private beach at sunset', 'Luxury hotel room balcony', 'Cozy cabin hot tub', 'Surprise road trip car stop'],
  },
  {
    category_id: '633ebce0-183b-4fbe-a9da-dafb36fe6a17',
    question_text: 'What do I value most in a lifelong partnership?',
    answer_type: 'multiple_choice',
    options: ['Unconditional trust & honesty', 'Deep emotional intimacy', 'Laughter & shared joy', 'Growth & mutual support'],
  },
  {
    category_id: '633ebce0-183b-4fbe-a9da-dafb36fe6a17',
    question_text: 'What is my biggest personal fear about the future?',
    answer_type: 'multiple_choice',
    options: ['Not fulfilling my potential', 'Losing people I love', 'Getting stuck in routine', 'Financial instability'],
  },
  {
    category_id: '633ebce0-183b-4fbe-a9da-dafb36fe6a17',
    question_text: 'When I am overwhelmed or stressed, how do I prefer to be comforted?',
    answer_type: 'multiple_choice',
    options: ['Give me space to process first', 'Listen to me vent without judgment', 'Distract me with humor and fun', 'Hold me tightly in silence'],
  },
  {
    category_id: '7352a310-464a-49ce-b491-6d1196c7bdee',
    question_text: 'What is my ultimate late-night comfort craving?',
    answer_type: 'multiple_choice',
    options: ['Ice cream / Sweets', 'Pizza / Cheesy bite', 'Spicy ramen or noodles', 'Crispy fries / Burgers'],
  },
  {
    category_id: '7352a310-464a-49ce-b491-6d1196c7bdee',
    question_text: 'If we could only eat one cuisine together for a whole month, what would I pick?',
    answer_type: 'multiple_choice',
    options: ['Italian (Pasta & Pizza)', 'Japanese (Sushi & Ramen)', 'Mexican (Tacos & Burritos)', 'Thai / Asian fusion'],
  },
  {
    category_id: '7352a310-464a-49ce-b491-6d1196c7bdee',
    question_text: 'How do I take my coffee or tea in the morning?',
    answer_type: 'multiple_choice',
    options: ['Sweet with cream & flavor syrups', 'Black / Strong with no sugar', 'I prefer iced boba or tea', 'Fruit smoothie or juice instead'],
  },
  {
    category_id: 'c02895de-079d-4300-baf9-727a19e58e66',
    question_text: 'What was my exact internal thought when we first met or started talking?',
    answer_type: 'multiple_choice',
    options: ['Wow, they are incredibly attractive', 'I feel so comfortable with them', 'This person is special', 'I could talk to them for hours'],
  },
  {
    category_id: 'c02895de-079d-4300-baf9-727a19e58e66',
    question_text: 'Which of our past memories do I bring up the most often?',
    answer_type: 'multiple_choice',
    options: ['Our first long late-night video call', 'Our airport reunion hug', 'That funny awkward moment we laughed at', 'Our first romantic dinner'],
  },
  {
    category_id: 'c02895de-079d-4300-baf9-727a19e58e66',
    question_text: 'What was the first thing about your profile or picture that caught my eye?',
    answer_type: 'multiple_choice',
    options: ['Your warm smile', 'Your eyes', 'Your style & vibe', 'The way you phrased your message'],
  },
  {
    category_id: 'd0a9567e-f400-414f-82a9-24f562d15067',
    question_text: 'If I was an animal, what would I be based on my personality?',
    answer_type: 'multiple_choice',
    options: ['A golden retriever puppy', 'A cozy lazy cat', 'A wise owl', 'A playful dolphin'],
  },
  {
    category_id: 'd0a9567e-f400-414f-82a9-24f562d15067',
    question_text: 'What weird talent or useless skill do I secretly possess?',
    answer_type: 'multiple_choice',
    options: ['Remembering random trivia facts', 'Doing funny voice impressions', 'Solving puzzles super fast', 'Wiggling ears / weird flexibility'],
  },
  {
    category_id: 'd0a9567e-f400-414f-82a9-24f562d15067',
    question_text: 'If I won $10 Million today, what is the first ridiculous thing I would buy?',
    answer_type: 'multiple_choice',
    options: ['A private jet to visit you anytime', 'A castle in Europe', 'A lifetime supply of my favorite food', 'A high-end sports car'],
  },
  {
    category_id: '342055b5-acbc-48d0-9347-0a09ec4217cc',
    question_text: 'What is my dream vacation style with you?',
    answer_type: 'multiple_choice',
    options: ['Relaxing beach resort with cocktails', 'Exploring historic cities & food tours', 'Hiking mountains & nature camping', 'Road trip across breathtaking coastlines'],
  },
  {
    category_id: '342055b5-acbc-48d0-9347-0a09ec4217cc',
    question_text: 'Which extreme adventure activity would I actually do with you?',
    answer_type: 'multiple_choice',
    options: ['Skydiving / Parasailing', 'Scuba diving with sea life', 'Ziplining over a jungle', 'Hot air balloon rides'],
  },
  {
    category_id: '6006c2f7-c451-427a-952b-485019438ca0',
    question_text: 'What is my biggest minor relationship ick?',
    answer_type: 'multiple_choice',
    options: ['Leaving messages on read for hours', 'Chewing loudly or noisy eating', 'Being indecisive about food', 'Being constantly late'],
  },
  {
    category_id: '6006c2f7-c451-427a-952b-485019438ca0',
    question_text: 'What texting habit annoys me the most?',
    answer_type: 'multiple_choice',
    options: ['One-word replies like "K"', 'Using too many ellipses (...)', 'Sending 15 separate tiny messages', 'Voice notes that are 10 minutes long'],
  },
  {
    category_id: 'abf5d323-6501-4d27-ac32-b2441c85c940',
    question_text: 'What was my favorite childhood hobby growing up?',
    answer_type: 'multiple_choice',
    options: ['Video games & computer gear', 'Sports & outdoor games', 'Reading & drawing/art', 'Listening to music & dancing'],
  },
  {
    category_id: 'abf5d323-6501-4d27-ac32-b2441c85c940',
    question_text: 'What nostalgic 2000s / 2010s trend do I secretly miss?',
    answer_type: 'multiple_choice',
    options: ['Classic Cartoon Network / Nickelodeon shows', 'Old school MP3 players & iPods', 'Retro arcade games', 'Flip phones & MSN messenger'],
  },
  {
    category_id: 'eaf58a21-7ade-4b03-9c21-d4ade4f75032',
    question_text: 'What is my biggest dream when we finally close the distance forever?',
    answer_type: 'multiple_choice',
    options: ['Building our cozy dream home together', 'Traveling the world side-by-side', 'Cooking dinner together every single night', 'Adopting a cute pet together'],
  },
  {
    category_id: 'eaf58a21-7ade-4b03-9c21-d4ade4f75032',
    question_text: 'What pet do I want us to get when we live under the same roof?',
    answer_type: 'multiple_choice',
    options: ['A fluffy dog', 'A cute cat', 'Two pets so they aren\'t lonely', 'No pets, just us traveling'],
  },
  {
    category_id: '62df1e57-3984-474d-a891-e2794be9d6fd',
    question_text: 'What is a little secret habit I have when I think no one is watching?',
    answer_type: 'multiple_choice',
    options: ['Singing loudly in the shower/car', 'Dancing randomly when happy', 'Checking my hair/outfit in mirrors', 'Re-reading your sweet texts'],
  },
  {
    category_id: '62df1e57-3984-474d-a891-e2794be9d6fd',
    question_text: 'What is a funny confession I haven\'t told many people?',
    answer_type: 'multiple_choice',
    options: ['I used to fake being sick to stay home & play games', 'I once ate a whole cake by myself in one sitting', 'I practiced my romantic speech in the mirror', 'I stalked your social media before our first date'],
  },
  {
    category_id: '987b773f-494f-484a-a100-1c127dfc8eeb',
    question_text: 'What is my most controversial food or life hot take?',
    answer_type: 'multiple_choice',
    options: ['Pineapple DOES belong on pizza', 'Cold pizza is better than hot pizza', 'Movie theaters are overrated', 'Morning people have secret superpowers'],
  },
  {
    category_id: '987b773f-494f-484a-a100-1c127dfc8eeb',
    question_text: 'What is my hot take on romantic comedy tropes?',
    answer_type: 'multiple_choice',
    options: ['The airport chase scene is classic gold', 'Miscommunication plots are super annoying', 'Enemies-to-lovers is the best trope', 'Friends-to-lovers is superior'],
  },
  {
    category_id: '4427023a-f221-464c-b00b-70c383977f07',
    question_text: 'If a Zombie Apocalypse happened, what would my role in our duo be?',
    answer_type: 'multiple_choice',
    options: ['The strategic planner & supply seeker', 'The fierce protector & fighter', 'The medic & emotional support anchor', 'The one who accidentally makes a noise'],
  },
  {
    category_id: '4427023a-f221-464c-b00b-70c383977f07',
    question_text: 'If we could time travel to any era for one week, where would I take us?',
    answer_type: 'multiple_choice',
    options: ['The Roaring 1920s Jazz Era', 'Ancient Egypt or Greece', 'The Futuristic 2150 AD', 'The 1980s Disco & Synthwave Era'],
  },
];
