export const thisOrThatQuestions = [
  { game_slug: 'this-or-that', question_text: 'Coffee or Tea?', answer_type: 'this_or_that', options: ['☕ Coffee', '🍵 Tea'] },
  { game_slug: 'this-or-that', question_text: 'Cats or Dogs?', answer_type: 'this_or_that', options: ['🐱 Cats', '🐶 Dogs'] },
  { game_slug: 'this-or-that', question_text: 'Netflix Night or Nightclub Party?', answer_type: 'this_or_that', options: ['🎬 Netflix & Chill', '🪩 Party Nightclub'] },
  { game_slug: 'this-or-that', question_text: 'Pizza or Burgers?', answer_type: 'this_or_that', options: ['🍕 Cheesy Pizza', '🍔 Juicy Burger'] },
  { game_slug: 'this-or-that', question_text: 'Beach Holiday or Mountain Cabin?', answer_type: 'this_or_that', options: ['🏖️ Sunny Beach', '⛰️ Cozy Cabin'] },
  { game_slug: 'this-or-that', question_text: 'Early Morning Bird or Late Night Owl?', answer_type: 'this_or_that', options: ['🌅 Early Bird', '🌙 Night Owl'] },
  { game_slug: 'this-or-that', question_text: 'Sweet Snacks or Savory Treats?', answer_type: 'this_or_that', options: ['🍦 Sweet Dessert', '🍿 Savory Snacks'] },
  { game_slug: 'this-or-that', question_text: 'Road Trip or Flight Getaway?', answer_type: 'this_or_that', options: ['🚗 Scenic Road Trip', '✈️ Fast Flight'] },
  { game_slug: 'this-or-that', question_text: 'Cook at Home or Order Takeout?', answer_type: 'this_or_that', options: ['👩‍🍳 Cook Together', '📱 Order Takeout'] },
  { game_slug: 'this-or-that', question_text: 'Texting All Day or 1 Long Video Call?', answer_type: 'this_or_that', options: ['💬 Constant Texting', '📹 Nightly Video Call'] },
  { game_slug: 'this-or-that', question_text: 'Pancakes or Waffles?', answer_type: 'this_or_that', options: ['🥞 Pancakes', '🧇 Waffles'] },
  { game_slug: 'this-or-that', question_text: 'Summer or Winter?', answer_type: 'this_or_that', options: ['☀️ Summer', '❄️ Winter'] },
  { game_slug: 'this-or-that', question_text: 'Comedy or Horror Movie?', answer_type: 'this_or_that', options: ['😂 Comedy', '👻 Horror'] },
  { game_slug: 'this-or-that', question_text: 'iOS or Android?', answer_type: 'this_or_that', options: ['🍎 iOS', '🤖 Android'] },
  { game_slug: 'this-or-that', question_text: 'Introvert or Extrovert?', answer_type: 'this_or_that', options: ['🤫 Introvert', '🥳 Extrovert'] },
  { game_slug: 'this-or-that', question_text: 'Read a Book or Watch a Movie?', answer_type: 'this_or_that', options: ['📚 Book', '🎬 Movie'] },
  { game_slug: 'this-or-that', question_text: 'Call or Text?', answer_type: 'this_or_that', options: ['📞 Call', '💬 Text'] },
  { game_slug: 'this-or-that', question_text: 'Dine In or Delivery?', answer_type: 'this_or_that', options: ['🍽️ Dine In', '🛵 Delivery'] },
  { game_slug: 'this-or-that', question_text: 'Money or Free Time?', answer_type: 'this_or_that', options: ['💰 Money', '⏳ Free Time'] },
  { game_slug: 'this-or-that', question_text: 'Gold or Silver?', answer_type: 'this_or_that', options: ['🥇 Gold', '🥈 Silver'] },
  { game_slug: 'this-or-that', question_text: 'Fast Food or Fancy Restaurant?', answer_type: 'this_or_that', options: ['🍟 Fast Food', '🥂 Fancy Restaurant'] },
  { game_slug: 'this-or-that', question_text: 'Tattoos or Piercings?', answer_type: 'this_or_that', options: ['🖋️ Tattoos', '💎 Piercings'] },
  { game_slug: 'this-or-that', question_text: 'City Life or Countryside?', answer_type: 'this_or_that', options: ['🏙️ City Life', '🏡 Countryside'] },
  { game_slug: 'this-or-that', question_text: 'Sneakers or Dress Shoes?', answer_type: 'this_or_that', options: ['👟 Sneakers', '👞 Dress Shoes'] },
  { game_slug: 'this-or-that', question_text: 'Working out at Home or the Gym?', answer_type: 'this_or_that', options: ['🏠 Home', '🏋️ Gym'] },
  { game_slug: 'this-or-that', question_text: 'Shower in the Morning or at Night?', answer_type: 'this_or_that', options: ['🌅 Morning', '🌃 Night'] },
  { game_slug: 'this-or-that', question_text: 'Marvel or DC?', answer_type: 'this_or_that', options: ['🦸‍♂️ Marvel', '🦇 DC'] },
  { game_slug: 'this-or-that', question_text: 'Pop or R&B?', answer_type: 'this_or_that', options: ['🎤 Pop', '🎶 R&B'] },
  { game_slug: 'this-or-that', question_text: 'Save or Spend?', answer_type: 'this_or_that', options: ['🏦 Save', '💸 Spend'] },
  { game_slug: 'this-or-that', question_text: 'Rollercoaster or Ferris Wheel?', answer_type: 'this_or_that', options: ['🎢 Rollercoaster', '🎡 Ferris Wheel'] }

];
