export const wouldYouRatherQuestions = [
  { game_slug: 'would-you-rather', question_text: 'Would you rather have a cozy home movie date or a fancy candlelit dinner?', answer_type: 'this_or_that', options: ['🛋️ Home Movie Date', '🕯️ Fancy Dinner'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather live in a bustling metropolis or a quiet seaside town?', answer_type: 'this_or_that', options: ['🏙️ Big City', '🌊 Seaside Town'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather travel 100 years into the past or 100 years into the future?', answer_type: 'this_or_that', options: ['⏳ 100 Years Past', '🚀 100 Years Future'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather have infinite free coffee or infinite free flights to see each other?', answer_type: 'this_or_that', options: ['☕ Infinite Coffee', '✈️ Unlimited Flights'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather receive surprise flowers or a hand-written love letter?', answer_type: 'this_or_that', options: ['💐 Surprise Flowers', '💌 Hand-written Letter'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather spend a rainy weekend sleeping in or exploring a new city?', answer_type: 'this_or_that', options: ['🛌 Cozy Sleep-in', '🌆 Explore City'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather be able to read minds or telepathically talk only to your partner?', answer_type: 'this_or_that', options: ['🧠 Read All Minds', '💞 Partner Telepathy'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather have the ability to fly or be invisible?', answer_type: 'this_or_that', options: ['🕊️ Fly', '👻 Invisible'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather always be 10 minutes late or always be 20 minutes early?', answer_type: 'this_or_that', options: ['⏰ 10 Mins Late', '⏳ 20 Mins Early'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather lose all of your money and valuables or all of the pictures you have ever taken?', answer_type: 'this_or_that', options: ['💸 Lose Money', '📸 Lose Pictures'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather be able to talk with all animals or speak all foreign languages?', answer_type: 'this_or_that', options: ['🐾 Talk to Animals', '🌍 Speak all Languages'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather have a time machine that can only go back in time or one that can only go forward in time?', answer_type: 'this_or_that', options: ['⏪ Go Back', '⏩ Go Forward'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather give up your smartphone or your computer for a month?', answer_type: 'this_or_that', options: ['📱 Smartphone', '💻 Computer'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather never have to sleep or never have to eat?', answer_type: 'this_or_that', options: ['🚫😴 No Sleep', '🚫🍽️ No Eat'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die?', answer_type: 'this_or_that', options: ['🌟 Famous Alive', '🌟 Famous Dead'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather go to jail for 4 years for something you didn\'t do or get away with something horrible but always live in fear of being caught?', answer_type: 'this_or_that', options: ['⛓️ Jail 4 Years', '😨 Live in Fear'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather accidentally be responsible for the death of a child or accidentally be responsible for the death of 3 adults?', answer_type: 'this_or_that', options: ['👶 1 Child', '👨‍👩‍👧 3 Adults'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather your shirts be always two sizes too big or one size too small?', answer_type: 'this_or_that', options: ['👕 Two Sizes Too Big', '👕 One Size Too Small'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather live without the internet or live without AC and heating?', answer_type: 'this_or_that', options: ['📶 No Internet', '🌡️ No AC/Heating'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather be able to control fire or water?', answer_type: 'this_or_that', options: ['🔥 Control Fire', '💧 Control Water'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather have a completely automated home or a self-driving car?', answer_type: 'this_or_that', options: ['🏠 Automated Home', '🚗 Self-driving Car'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather work a high-paying job that you hate or a low-paying job that you love?', answer_type: 'this_or_that', options: ['💰 Hate Job', '❤️ Love Job'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather be able to read minds but everyone knows you can or have invisibility but only for 10 minutes a day?', answer_type: 'this_or_that', options: ['🧠 Read Minds (Known)', '👻 Invisible (10 mins)'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather only eat pizza for a year or only eat tacos for a year?', answer_type: 'this_or_that', options: ['🍕 Pizza Only', '🌮 Tacos Only'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather have unlimited free food at any restaurant or unlimited free flights?', answer_type: 'this_or_that', options: ['🍽️ Free Food', '✈️ Free Flights'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather end world hunger or stop climate change?', answer_type: 'this_or_that', options: ['🍲 End Hunger', '🌍 Stop Climate Change'] },
  { game_slug: 'would-you-rather', question_text: 'Would you rather never age physically or never age mentally?', answer_type: 'this_or_that', options: ['🧍 Never Age Physically', '🧠 Never Age Mentally'] }

];
